site_name: Hype
site_description: A lightweight command line interface toolkit for python
site_url: https://hype.serum.studio

repo_name: serumstudio/hype
repo_url: https://github.com/serumstudio/hype
repo_branch: main

copyright: Copyright &copy; 2020 - 2021, Serum Studio

theme:
  favicon: images/favicon.ico
  name: material
  palette:
    - scheme: default
      primary: black
      accent: purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    
    - scheme: slate
      primary: black
      accent: purple
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

  features:
    - navigation.tracking
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - navigation.sections

  plugins:
    - search
    - tags

nav:
  - Getting started:
    - index.md
    - Installation: getting-started.md
    - Features: features.md
  
  - Commands:
    - commands/index.md
    - Handling Commands: commands/handling-commands.md

  - Plugins:
    - plugins/index.md
    - Handling Colors: plugins/colors.md
